In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel(r"C:\Users\HP\Downloads\Amazon-Sales-Report-80K-Rows.xlsx")

In [3]:
df.head()

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Category,Size,Courier Status,Qty,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,B2B,fulfilled-by
0,0,405-8078784-5731545,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,T-shirt,S,On the Way,0,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,False,Easy Ship
1,1,171-9198151-1101146,2022-04-30,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,Shirt,3XL,Shipped,1,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,False,Easy Ship
2,2,404-0687676-7273146,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,Shirt,XL,Shipped,1,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,True,NaN
3,3,403-9615377-8133951,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,Blazzer,L,On the Way,0,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,False,Easy Ship
4,4,407-1069790-7240320,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,Trousers,3XL,Shipped,1,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,False,NaN

In [4]:
df.describe()

,index,Date,Qty,Amount,ship-postal-code
count,79999.000000,79999,79999.000000,75236.000000,79977.00000
mean,39997.404168,2022-04-28 10:45:10.923886592,0.901811,643.873211,462878.02452
min,0.000000,2022-03-31 00:00:00,0.000000,0.000000,110001.00000
25%,19998.500000,2022-04-13 00:00:00,1.000000,448.570000,380051.00000
50%,39998.000000,2022-04-24 00:00:00,1.000000,599.000000,500025.00000
75%,59997.500000,2022-05-15 00:00:00,1.000000,788.000000,600032.00000
max,79997.000000,2022-05-31 00:00:00,15.000000,5584.000000,989898.00000
std,23094.766434,NaN,0.320857,278.664910,193357.63500

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79999 entries, 0 to 79998
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   index               79999 non-null  int64
 1   Order ID            79999 non-null  object
 2   Date                79999 non-null  datetime64[ns]
 3   Status              79999 non-null  object
 4   Fulfilment          79999 non-null  object
 5   Sales Channel       79999 non-null  object
 6   ship-service-level  79999 non-null  object
 7   Category            79999 non-null  object
 8   Size                79999 non-null  object
 9   Courier Status      79999 non-null  object
 10  Qty                 79999 non-null  int64
 11  currency            75236 non-null  object
 12  Amount              75236 non-null  float64
 13  ship-city           79977 non-null  object
 14  ship-state          79977 non-null  object
 15  ship-postal-code    79977 non-null  float64
 16  ship-country        79977 non-null  object
 17  B2B                 79999 non-null  bool
 18  fulfilled-by        26623 non-null  object
dtypes: bool(1), datetime64[ns](1), float64(2), int64(2), object(13)
memory usage: 11.1+ MB

In [6]:
df.columns

Index(['index', 'Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel',
       'ship-service-level', 'Category', 'Size', 'Courier Status', 'Qty',
       'currency', 'Amount', 'ship-city', 'ship-state', 'ship-postal-code',
       'ship-country', 'B2B', 'fulfilled-by'],
      dtype='object')

In [7]:
df.columns.str.replace(" ","-")

Index(['index', 'Order-ID', 'Date', 'Status', 'Fulfilment', 'Sales-Channel',
       'ship-service-level', 'Category', 'Size', 'Courier-Status', 'Qty',
       'currency', 'Amount', 'ship-city', 'ship-state', 'ship-postal-code',
       'ship-country', 'B2B', 'fulfilled-by'],
      dtype='object')

In [8]:
df.duplicated().sum()

168

In [9]:
df = df.drop_duplicates()

In [10]:
df.isnull().sum()

index                     0
Order ID                  0
Date                      0
Status                    0
Fulfilment                0
Sales Channel             0
ship-service-level        0
Category                  0
Size                      0
Courier Status            0
Qty                       0
currency               4752
Amount                 4752
ship-city                20
ship-state               20
ship-postal-code         20
ship-country             20
B2B                       0
fulfilled-by          53258
dtype: int64

In [11]:
df['currency'] = df['currency'].fillna('INR')

In [12]:
df['Amount'] = df['Amount'].fillna(0)

In [13]:
df['fulfilled-by'].unique()

array(['Easy Ship', nan], dtype=object)

In [14]:
df['fulfilled-by'] = df['fulfilled-by'].replace('Easy Ship','amazon')
df['fulfilled-by'] = df['fulfilled-by'].fillna('merchant')

In [21]:
df['ship-city'] = df['ship-city'].fillna('unknown')
df['ship-state'] = df['ship-state'].fillna('unknown')
df['ship-country'] = df['ship-country'].replace('unknown','IN')
df['ship-country'] = df['ship-country'].replace('IN','INDIA')
df['ship-postal-code'] = df['ship-postal-code'].fillna('unknown')

In [22]:
df['ship-country'].unique()

array(['INDIA'], dtype=object)

In [23]:
df.to_csv("amazon_sales_cleaned.csv",index=False)